import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Nav() {
  const pathname = typeof window !== 'undefined' ? window.location.pathname : '';
  const links = [
    { href: "/", label: "Novo Orçamento" },
    { href: "/partes-processo", label: "Partes do Processo" },
    { href: "/trabalhos", label: "Trabalhos" },
    { href: "/orcamentos", label: "Orçamentos Salvos" },
  ];
  return (
    <nav className="w-full bg-white shadow-md py-4 px-6 flex justify-center items-center fixed top-0 left-0 z-20 border-b border-zinc-200">
      <div className="flex gap-8 items-center w-full max-w-5xl mx-auto">
        <Link href="/" className="flex items-center mr-6 group">
          <Image 
            src="/RE9.png" 
            alt="Logo RE9" 
            width={120}
            height={56}
            className="h-14 w-auto mr-2 transition-transform group-hover:scale-105" 
            style={{maxHeight:56}}
            priority
          />
        </Link>
        <div className="flex gap-8 items-center flex-1 justify-center">
          {links.map(link => {
            const isActive = pathname === link.href || (link.href !== '/' && pathname.startsWith(link.href));
            return (
              <Link
                key={link.href}
                href={link.href}
                className={
                  `relative font-medium px-4 py-2 rounded-xl transition-colors duration-150 flex items-center gap-2 text-base ` +
                  (isActive
                    ? "text-white bg-blue-700 shadow font-bold after:absolute after:-bottom-1 after:left-3 after:right-3 after:h-1 after:bg-blue-400 after:rounded"
                    : "text-zinc-800 hover:text-blue-700 hover:bg-blue-50")
                }
                aria-current={isActive ? "page" : undefined}
              >
                {isActive && (
                  <span className="w-2 h-2 bg-blue-400 rounded-full mr-1 animate-pulse" aria-hidden="true"></span>
                )}
                {link.label}
              </Link>
            );
          })}
        </div>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className="bg-zinc-100 text-zinc-900 min-h-screen font-sans">
        <Nav />
        <main className="pt-32 max-w-4xl mx-auto px-4 sm:px-8">
          <div className="bg-white rounded-2xl shadow-lg p-8 min-h-[70vh] border border-zinc-200">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
