import type { Metadata } from "next";
import "./globals.css";
import { Nav } from "./components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className="bg-zinc-100 text-zinc-900 min-h-screen font-sans">
        <Nav />
        <main className="pt-32 max-w-4xl mx-auto px-4 sm:px-8">
          <div className="bg-white rounded-2xl shadow-lg p-8 min-h-[70vh] border border-zinc-200">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
